basePath: /api
definitions:
  controllers.ErrorResponse:
    description: Standard error response format
    properties:
      error:
        description: Error message
        example: Invalid credentials
        type: string
      message:
        description: Additional message
        example: Authentication failed
        type: string
    type: object
  controllers.LoginRequest:
    description: User login request payload
    properties:
      password:
        description: User's password
        example: password123
        type: string
      username:
        description: User's username
        example: john_doe
        type: string
    type: object
  controllers.LoginResponse:
    description: Authentication response with JWT token
    properties:
      token:
        description: JWT token
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
      user:
        description: User information
        properties:
          email:
            description: User email
            example: john@example.com
            type: string
          id:
            description: User ID
            example: 1
            type: integer
          username:
            description: Username
            example: john_doe
            type: string
        type: object
    type: object
host: localhost:6000
info:
  contact: {}
  description: API for educational platform
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Learning Platform API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate user and return JWT token
      parameters:
      - description: Login credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controllers.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: User login
      tags:
      - auth
schemes:
- http
swagger: "2.0"
